const API_LOADING_START = 'API_LOADING_START';
const API_LOADING_SUCCESS = 'API_LOADING_SUCCESS';
const API_LOADING_ERROR = 'API_LOADING_ERROR';
const NULLIFY_ERROR = 'NULLIFY_ERROR';
const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';

const AUTH_SIGN = 'AUTH_SIGN';

const GET_PRODUCTS = 'GET_PRODUCTS';

export {
  API_LOADING_START,
  API_LOADING_SUCCESS,
  API_LOADING_ERROR,
  NULLIFY_ERROR,
  RESET_INITIAL_STATE,
  AUTH_SIGN,
  GET_PRODUCTS,
};
