// GENERAL
const API_LOADING_START = "API_LOADING_START";
const API_LOADING_SUCCESS = "API_LOADING_SUCCESS";
const API_LOADING_ERROR = "API_LOADING_ERROR";
const NULLIFY_ERROR = "NULLIFY_ERROR";

// AUTH
const AUTH_SIGN = "AUTH_SIGN";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";
const REGISTERED_TRUE = "REGISTERED_TRUE";
const CHANGE_PERMITTED = "CHANGE_PERMITTED";
const WANT_TO_CHANGE_PASS = "WANT_TO_CHANGE_PASS";
const GET_CHANGE_PASSWORD_USER_DATA = "GET_CHANGE_PASSWORD_USER_DATA";

// PRODUCT
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";

// CART
const GET_CART = "GET_CART";

// ADMIN
const GET_DASHBOARD = "GET_DASHBOARD";
const GET_ADMIN_PRODUCTS = "GET_ADMIN_PRODUCTS";
const GET_WAREHOUSE = "GET_WAREHOUSE";

// API DAERAH
const GET_DATA_DAERAH = "GET_DATA_DAERAH";
const RESET_DAERAH_INITIAL_STATE = "RESET_DAERAH_INITIAL_STATE";

export {
	API_LOADING_START,
	API_LOADING_SUCCESS,
	API_LOADING_ERROR,
	NULLIFY_ERROR,
	AUTH_SIGN,
	AUTH_LOGOUT,
	GET_PRODUCTS,
	GET_PRODUCTS_ID,
	RESET_INITIAL_STATE,
	REGISTERED_TRUE,
	CHANGE_PERMITTED,
	GET_DASHBOARD,
	WANT_TO_CHANGE_PASS,
	GET_CHANGE_PASSWORD_USER_DATA,
	GET_CART,
	GET_DATA_DAERAH,
	RESET_DAERAH_INITIAL_STATE,
	GET_ADMIN_PRODUCTS,
	GET_WAREHOUSE,
};
