const API_LOADING_START = "API_LOADING_START";
const API_LOADING_SUCCESS = "API_LOADING_SUCCESS";
const API_LOADING_ERROR = "API_LOADING_ERROR";
const NULLIFY_ERROR = "NULLIFY_ERROR";
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";
const AUTH_SIGN = "AUTH_SIGN";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";
const REGISTERED_TRUE = "REGISTERED_TRUE";
const CHANGE_PERMITTED = "CHANGE_PERMITTED";
const GET_DASHBOARD = "GET_DASHBOARD";

export {
	API_LOADING_START,
	API_LOADING_SUCCESS,
	API_LOADING_ERROR,
	NULLIFY_ERROR,
	AUTH_SIGN,
	AUTH_LOGOUT,
	GET_PRODUCTS,
	GET_PRODUCTS_ID,
	RESET_INITIAL_STATE,
	REGISTERED_TRUE,
	CHANGE_PERMITTED,
	GET_DASHBOARD,
};
